# Generated by Django 4.0.5 on 2022-07-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_cart_id_alter_cart_temp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='temp_id',
            new_name='id',
        ),
    ]
